name: NDK build
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**.yml'
      - '!.github/workflows/BuildMod.yml'
      - '**.json'
      - '!qpm.json'
      - '**.ps1'
      - '!build.ps1'
      - '!buildQMOD.ps1'
      - '**.md'
      - '.gitignore'
      - '**.zip'
env:
     module_id: mymod
     version: 0.1.0-Dev.${{ github.run_number }}

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
    - uses: actions/checkout@v2
      name: Checkout
      with:
        submodules: true
        lfs: true 
    - uses: seanmiddleditch/gha-setup-ninja@v3
    - name: Setup Android NDK
      # You may pin to the exact commit or the version.
      # uses: nttld/setup-ndk@b2abc75192ee2a1ec118c8238fd86dec6d96dc43
      uses: nttld/setup-ndk@v1.0.6
      with:
        # Exact version to use
        ndk-version: r23c
        # Add installation directory to path
        add-to-path: true
    - name: Print directory structure
      # You may pin to the exact commit or the version.
      # uses: FiorelaCiroku/XDTesting-Print-Directory-Structure@553df9b35280b89f01b0f3e4d93d9171095a55d4
      uses: FiorelaCiroku/XDTesting-Print-Directory-Structure@v1.0.2
    - name: Build using QPM and NDK
      # You may pin to the exact commit or the version.
      # uses: sc2ad/QuestNDKBuildAction@b697f685e75bcf87f50ca95ea5f4baa7e99a9793
      uses: sc2ad/QuestNDKBuildAction@v0.1.1
      with:
        # Github token
        github_token: ${{ secrets.GITHUB_TOKEN }}
        # Github workspace
        workspace: ./extern\beatsaber-hook
        # The library prefix to use. Should be the QPM ID.
        libname: beatsaber-hook
    - run: "ndk-build NDK_PROJECT_PATH=. APP_BUILD_SCRIPT=./Android.mk NDK_APPLICATION_MK=./Application.mk"
   # - name: Upload a Build Artifact
   #   uses: actions/upload-artifact@v3.1.0
   #   with:
   #     # Artifact name
   #     name: Build
   #     path: 
   #     # The desired behavior if no files are found using the provided path.
 
        
