name: NDK build
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**.yml'
      - '!.github/workflows/BuildMod.yml'
      - '**.json'
      - '!qpm.json'
      - '**.ps1'
      - '!build.ps1'
      - '!buildQMOD.ps1'
      - '**.md'
      - '.gitignore'
      - '**.zip'
env:
     module_id: mymod
     version: 0.1.0-Dev.${{ github.run_number }}

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
    - uses: actions/checkout@v2
      name: Checkout
      with:
        submodules: true
        lfs: true 
    - uses: seanmiddleditch/gha-setup-ninja@v3
    - name: Setup Android NDK
      # You may pin to the exact commit or the version.
      # uses: nttld/setup-ndk@b2abc75192ee2a1ec118c8238fd86dec6d96dc43
      uses: nttld/setup-ndk@v1.0.6
      with:
        # Exact version to use
        ndk-version: r23c
        # Add installation directory to path
        add-to-path: true
    - name: Print directory structure
      # You may pin to the exact commit or the version.
      # uses: FiorelaCiroku/XDTesting-Print-Directory-Structure@553df9b35280b89f01b0f3e4d93d9171095a55d4
      uses: FiorelaCiroku/XDTesting-Print-Directory-Structure@v1.0.2
    - run: "git clone https://github.com/RedBrumbler/QuestPackageManager-Rust.git; cd QuestPackageManager-Rust;"
    - name: rust-cargo
      # You may pin to the exact commit or the version.
      # uses: actions-rs/cargo@ae10961054e4aa8b4aa7dffede299aaf087aa33b
      uses: actions-rs/cargo@v1.0.1
      with:
        # Cargo command to run (ex. `check` or `build`)
        command: build
        # Toolchain to use (without the `+` sign, ex. `nightly`)
        toolchain: stable
        # Arguments for the cargo command
        args: --release
    - run: "cd ../extern/beatsaber-hook; ./target/release/qpm-rust restore"
    - run: "cd ..; ndk-build NDK_PROJECT_PATH=. APP_BUILD_SCRIPT=./Android.mk NDK_APPLICATION_MK=./Application.mk"
   # - name: Upload a Build Artifact
   #   uses: actions/upload-artifact@v3.1.0
   #   with:
   #     # Artifact name
   #     name: Build
   #     path: 
   #     # The desired behavior if no files are found using the provided path.
 
        
